#!/usr/bin/env bash
# manages manage_my_process file

err="Usage: manage_my_process {start|stop|restart}"

if [ -z "$1" ]
then
    echo "$err"
    exit
    
fi

case $1 in
    "start")
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    "stop")
	pkill -f ./manage_my_process
	rm -r /var/run/my_process.pid
	echo "manage_my_process stopped"
        ;;
    "restart")
	pkill -f ./manage_my_process
        rm -r /var/run/my_process.pid
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
        ;;
    *)
	echo "$err"
	exit
	;;
esac
